version: "3.7"
services:
  fastapi_project:
    image: fastapi_project
    container_name: fastapi_project_app
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - .:/fastapi_project
    depends_on:
      - db_project

  db_project:
    image: postgres:13.5-alpine
    container_name: fastapi_project_db
    volumes:
      - pgdata_project:/var/lib/postgresql/data_project
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastpi_project


volumes:
  pgdata_project:
    name: fastapi_db_project
    driver: local